### PR TITLE
fix: cv-tabs fails in focusout event when using router-link in a tab

### LINKED ISSUE #1083: cv-tabs fails in focusout event when using router-link in a tab
## Detailed description

> Describe in detail the issue you're having.

We use NuxtJS in one of our projects and have @carbon/vue for UI elements. On one of our "detailed view", we use the `cv-tabs` and `cv-tab` components and we have a `router-link` in one of the tabs. The issue we are experiencing is that after  clicking on the `router-link` in a `cv-tab`, the `cv-tabs` component's focusout event listener gets called and uses the `trigger` reference as a parameter in a `window.getComputedStyle` function call, which raises the following error:

```
client.js?06a0:96 TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at VueComponent.onFocusout (cv-tabs.vue?e464:125)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at HTMLDivElement.invoker (vue.runtime.esm.js?2b0e:2179)
    at HTMLDivElement.original._wrapper (vue.runtime.esm.js?2b0e:6917)
    at Object.removeChild (vue.runtime.esm.js?2b0e:5713)
    at removeNode (vue.runtime.esm.js?2b0e:5884)
    at remove$$1 (vue.runtime.esm.js?2b0e:5873)
    at eval (vue.runtime.esm.js?2b0e:7695)
    at eval (vue.runtime.esm.js?2b0e:336)
    at whenTransitionEnds (vue.runtime.esm.js?2b0e:7391)
```

> Is this issue related to a specific component?

Yes, this is related to the `cv-tabs` component.

> What did you expect to happen? What happened instead? What would you like to see changed?

I would expect to navigate to the page with the `router-link` without an error, but the next page fails to load because of this issue.

> What browser are you working in?

Google Chrome 87.0.4280.67 

> What version of the Carbon Design System are you using?

I'm experiencing the issue in the latest `v1.35.0` version too. Based on the commit history and my own experience, this bug is in there since multiple versions.

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

My project has a strict deadline, so this issue is a high priority for me and my team, I'm creating a PR really soon which I hope you can review and merge if you find it correct.

### PR DESCRIPTION
**Pull request by Fontinalis**
Closes #1083

This PR changes the `cv-tabs` component, adds the event listeners on `mount` and removes them in `beforeDestroy`, doing this with `this.$refs.tabs` where `tabs` is the root div which previously had the listeners attached as `@focusout="onFocusout" @focusin="onFocusin"`.

#### Changelog

M       packages/core/src/components/cv-tabs/cv-tabs.vue

### CODE REVIEW

**Comment by Fontinalis** [comment]
Hey @leechase99, 

First, thank you so much for maintaining this package, it's awesome and we love it. On the other hand, when you have a little time, can you please check this PR? Based on my tests, it fixed the issue and the code is right, but of course, I'm happy to take some comments.

**Comment by Fontinalis** [comment]
Hey @lee-chase,
Can you please review this? I know you are probably busy, and I do respect your time. We're just in a situation where this issue is keep popping up and slows us down.. In functionality, it doesn't change anything, the listeners are working the same way, it just removes the listeners from the `cv-tabs` component before destroying it so this error is not thrown. 
Thanks again for your work on the project!

**Review by lee-chase — COMMENTED** [review]
Looks good although I'm usually keen to observer an issue before trying to fix it. Can you create a code sandbox demonstrating the issue?

**Comment by Fontinalis** [comment]
Here's what I meant [https://codesandbox.io/s/eager-poitras-7lo88?file=/pages/index.vue](https://codesandbox.io/s/eager-poitras-7lo88?file=/pages/index.vue)

**Review by lee-chase — APPROVED** [review]

**Pull request merged**
