### PR TITLE
feat: add cv-modal

### PR DESCRIPTION
**Pull request by davidnixon**
Contributes to #1454

## What did you do?
Port cv-modal to Vue 3

## How have you tested it?
Added to storybook and unit tests

## Were docs updated if needed?

- [ ] Yes

### CODE REVIEW

**Comment by davidnixon** [comment]
@felipebritor could you review this one for me? Not sure why I can't assign you.

**Comment by felipebritor** [comment]
> @felipebritor could you review this one for me? Not sure why I can't assign you.

Sure. Today will be a full one, but I can review tomorrow, if thats ok.

**Comment by felipebritor** [comment]
Sorry for the delay, @davidnixon. 

There is only an issue at the story: since visible variables are set on file scope, its persisting the value when you switch between ` Canvas`  and `Docs` tabs. You can replicate by opening the modal and switching tabs, it will persist the modal state and open new ones.

The rest looks good to me!

**Comment by davidnixon** [comment]
@felipebritor That's a nice find. I fixed it but the fix is not perfect.
I found that the 2 refs controlling the visibility were stuck to "true" after clicking the show button. I resolved that but I still find that if a modal is open and then I switch tabs another modal opens but they all close when the "x" button is clicked. let me know what you think.

**Comment by felipebritor** [comment]
Sorry for the delay (again), @davidnixon. Its easier for me to respond at weekends.

I was currently checking and the modal open seems ok to me. But there seems to still be glitchy when switching tabs and clicking on open modal button, it open & closes the modal. Defining the visible refs at setup seems to solve it

**Comment by davidnixon** [comment]
oops. i merged too soon! I'll fix it with my next PR and tag you in it.

**Pull request merged**
