### PR TITLE
[v3] chore(deps): add @vueuse/core dependency

### PR DESCRIPTION
**Pull request by TimonLukas**
## What did you do?
Added `@vueuse/core` as a dependency for v3

## Why did you do it?
It seems like a great collection of re-usable Vue tools, which will lower our own implementation complexity.

### CODE REVIEW

**Comment by lee-chase** [comment]
Which parts of @vueuse/core were you thinking of using?

**Comment by TimonLukas** [comment]
Many functions could prove useful for us:
- [useDebounceFn](https://vueuse.org/shared/useDebounceFn/) for reactive debouncing (see my implementation of [`_CviCopyButton`](https://github.com/TimonLukas/carbon-components-vue/blob/71762d665d103b6e3209ac0ce55d1c54ac010964/packages/v3/src/components/CvCopyButton/_CviCopyButton.vue))
- [onClickOutside](https://vueuse.org/core/onClickOutside/) could be used for modals
- [useElementBounding](https://vueuse.org/core/useElementBounding/) will be very useful for code snippets
- [useClipboard](https://vueuse.org/core/useClipboard/) for code snippets
- [useVModels](https://vueuse.org/core/useVModels/) for components with v-models

This is just from a quick overview. I think there are a lot of functions in there that will make our lives a lot easier, and it doesn't have any sub-dependencies.

**Comment by hedphuqz** [comment]
Hi, so I also had a look at vue-use and I much prefer the idea of setting up v-models this way. It tightly couples our v-model names with our prop names which helps bring more uniformity to the code we're writing. 

I think also that utilities such as `useElementBounding` could simplify quite a lot of our work, especially when looking at tooltips for example.

I think one of the bigger advantages is it makes our code much more declarative and therefore easier to read and maintain.

**Review by lee-chase — APPROVED** [review]
OK. Lets use @vueuse/core

**Pull request merged**
