### PR TITLE
feat: add slot to gain control over tabs switching buttons

### PR DESCRIPTION
**Pull request by OlkaB**
Contributes to #1522

## What did you do?
Added slot to customise tab switching buttons' content

## How have you tested it?
added test for slot in CvTabs.spec.js

## Were docs updated if needed?
- [x] Yes

sample:
image

### CODE REVIEW

**Comment by davidnixon** [comment]
I like this solution but I think using the label is a problem. The Label would often be localized so the "House" label might become "Taigh" or "Maison" or "Casa". Could you use the id instead?

**Comment by OlkaB** [comment]
fair point - change applied

**Review by davidnixon — COMMENTED** [review]
sooooooo close:
"To customise tab look, in CvTabs component use scoped slot named with tab's **label**. Example: current tab has **label** "**House**", so the code for customising tab looks like:"

need to switch text to **id** :smile:

**Comment by OlkaB** [comment]
oh gosh - truly. Done, thanks @davidnixon

**Review by davidnixon — APPROVED** [review]
Thanks!

**Pull request merged**
