### PR TITLE
Replace node-sass on V3 & update eslint-plugin-vue

### PR DESCRIPTION
**Pull request by mateusbandeiraa**
## What did you do?
- Removed `node-sass` dev dependency
- Added dart-sass (`sass` version `^1.49.9`) dependency
- Updated `carbon-components` to version `^10.56.0`
- Updated `.yarn-offline-mirror` dependencies

## Why did you do it?
`node-sass` is now deprecated. New projects should be migrated to `dart-sass`.

I also updated `carbon-components` because building the current version generated lots of warnings for the usage of `/` as a division operator. Newer versions of `carbon-components` fix this issue.

## How have you tested it?
I ran `yarn serve` after making the changes and made sure the components were still working.
## Were docs updated if needed?

- [x] N/A
- [ ] No
- [ ] Yes

### CODE REVIEW

**Comment by mateusbandeiraa** [comment]
This PR is very similar to #1253

**Comment by mateusbandeiraa** [comment]
I added an update to `eslint-plugin-vue` (now at v8.5.0). Newer versions of the plugin fixes problems when using the newer `script setup` syntax.

Specifically, ESLint complained about unused variables if they were declared in the script but only used in the template.
screenhot of a terminal window with the output of the command `yarn lint`. There are many errors similar to 'WarningFilled16' is defined but never used (no-unused-vars)

Now, the errors will not show up if the variables are used in the template.
screenshot of a terminal window with the output of the command `yarn lint`. There are no errors.

**Comment by mateusbandeiraa** [comment]
I see the deploys failing with the following error in the netlify logs:
```log
9:46:23 PM: error eslint-plugin-vue@8.5.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "12.18.0"
```
@lee-chase Do we have the capability of changing netlify's node version? If not, we'll need to downgrade `eslint-plugin-vue` to [7.20.0](https://github.com/vuejs/eslint-plugin-vue/releases/tag/v7.20.0)

**Comment by lee-chase** [comment]
Fixed the node versions in Netlify to 14 for now, seems to have sorted the deploy.

**Review by lee-chase — APPROVED** [review]
LGTM

**Pull request merged**
