### PR TITLE
feat(component): add gauge component

### LINKED ISSUE #49: Add data-vis/gauge component
**Is your feature request related to a problem? Please describe.**
Add a Vue.js implementation of the carbon guage component http://www.carbondesignsystem.com/data-vis/gauge

**Describe the solution you'd like**
Single file templates, notes and story as per other components.

Ideally, it should not rely on core javascript.

**Describe alternatives you've considered**
Initial version can rely on core carbon javascript.

**Additional context**

### PR DESCRIPTION
**Pull request by ZrianinaMariia**
Closes #49 

Add gauge component with the following props: amount, total, header and suffix. It depends on d3 library.

#### Changelog

**New**

- gauge component, story and notes

**Changed**

- status of the gauge component in README

**Removed**

-

**Comments**

Many thanks to @rodet and @lee-chase for their help!

### CODE REVIEW

**Comment by lee-chase** [comment]
Thanks for the submission @ZrianinaMariia.

I am currently in discussion with the Carbon team as to where we should host the data-viz components. There may, as a result, be a delay in merging this PR.

**Comment by ZrianinaMariia** [comment]
Thanks for the update @lee-chase. May I ask is this discussion only about where to host data-viz components or should they be vue/react components at all? If I am not mistaken there are no react components for data-vis (http://react.carbondesignsystem.com/), only vanilla.

**Comment by lee-chase** [comment]
There are react components but they were moved out to https://github.com/carbon-design-system/carbon-addons-data-viz-react.

I have advocated adding a Vue repo similarly named.

The discussions I believe are about future versions of the design language.

**Comment by ZrianinaMariia** [comment]
Oh nice! I did not know that there are react components for data-viz. They are not mentioned on the website from my previous comment. Good to know.

Also half-gauge version is not mentioned here at all: https://www.carbondesignsystem.com/data-visualization/gauge/

**Comment by lee-chase** [comment]
I have updated to sb4 and tweaked your code to match, but I don't have permission to update your PR.

https://github.com/lee-chase/carbon-components-vue/tree/sb4-ZrianinaMariia-gauge-component

**Comment by ZrianinaMariia** [comment]
image

Thank you! I think you should have permissions to add commits to this PR (my branch). Or what kind of update do you mean?

**Comment by ZrianinaMariia** [comment]
Thank you! I think you should have permissions to add commits to this PR (my branch). Or what kind of update do you mean?

image

**Comment by lee-chase** [comment]
Hmm, not sure why it would not allow me to change it.

Go ahead and update your PR if possible.

There were manage changes (by me) to other stories and yarn offline.

**Comment by ZrianinaMariia** [comment]
I just added you as a collaborator for my fork (just in case). I will update my PR today/tomorrow. Thanks!

**Comment by ZrianinaMariia** [comment]
I added your last commit your mentioned above to my PR.

**Comment by lee-chase** [comment]
Hi @ZrianinaMariia Git confusion all around, I ended up with a separate PR. Please accept my apologies as it appears not to have credited me with your work.

We do now at least have a pattern for adding data-viz components. 

Folder
src/data-viz
dists/carbon-data-viz-vue...

The data-viz components will show at the bottom of the storybook as a separate section.

image

**Comment by ZrianinaMariia** [comment]
Hi @lee-chase, no problems. I am just glad that I could help!

**Pull request closed without merging**
