### PR TITLE
feat: port cv-structured-list to Vue3

### PR DESCRIPTION
**Pull request by OlkaB**
Contributes to #1511

## What did you do?
Port CvStructuredList to Vue3

## How have you tested it?
see spec.js files

## Were docs updated if needed?
- [ ] N/A
- [ ] No
- [x] Yes

### CODE REVIEW

**Comment by davidnixon** [comment]
Looks really nice. Thanks!

There are some warnings in the console. 
> [Vue warn]: Property "withVModel" was accessed during render but is not defined on instance
> [Vue warn]: Property "listValue" was accessed during render but is not defined on instance.
> runtime-core.esm-bundler.js:41 [Vue warn]: Property "onChange" was accessed during render but is not defined on instance.

Since both stories use the same template the default story still needs to define attributes:
```diff
--- a/src/components/CvStructuredList/CvStructuredList.stories.js
+++ b/src/components/CvStructuredList/CvStructuredList.stories.js
@@ -111,7 +111,10 @@ const Template = args => {
     },
     setup: () => ({
       args,
+      listValue: ref(DefaultListItems[0].id),
       DefaultListItems,
+      onChange: action('change'),
+      withVModel: false,
     }),
     template,
   };
```

**Review by davidnixon — CHANGES_REQUESTED** [review]
see comment

**Comment by OlkaB** [comment]
fixed. thank you @davidnixon

**Review by davidnixon — APPROVED** [review]
Thanks!

**Pull request merged**
