### PR TITLE
feat: add AccordionSkeleton and SkeletonText components

### PR DESCRIPTION
**Pull request by sabov**
#### Issue #167 

Adds `CvAccordionSkeleton` and `CvSkeletonText` components. Updates `CvAccordion` story.

#### Changelog

**New**

- `AccordionSkeleton`
- `SkeletonText` 

**Changed**

- `CvAccordion` story

#### Preview
skeleton

### CODE REVIEW

**Comment by sabov** [comment]
Hey @lee-chase, I was able to turn `CvAccordionItemSkeleton` to a functional component but it doesn't work for `CvAccordionSkeleton`. I'm getting this error when I add `functional` keyword to the template: 

```
vue.esm.js:628 [Vue warn]: Unknown custom element: <cv-accordion-item-skeleton> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in
---> <Anonymous>
       <Root>
```

Do you have any idea why?

**Comment by lee-chase** [comment]
Looks to be a known issue @sabov 

https://github.com/vuejs/vue/issues/7492

This works or we can use render functions.  Not sure it's worth the benefit. What do you think?

```
<template functional>
  <ul class="bx--accordion bx--skeleton">
    <component :is="injections.components.CvAccordionItemSkeleton" open>
      <component :is="injections.components.CvSkeletonText"/>
      <component :is="injections.components.CvSkeletonText"/>
      <component :is="injections.components.CvSkeletonText"/>
    </component>

    <component :is="injections.components.CvAccordionItemSkeleton"/>
    <component :is="injections.components.CvAccordionItemSkeleton"/>
    <component :is="injections.components.CvAccordionItemSkeleton"/>
  </ul>
</template>

<script>
import CvSkeletonText from '../cv-skeleton-text/cv-skeleton-text';
import CvAccordionItemSkeleton from './_cv-accordion-item-skeleton';

export default {
  name: 'CvAccordionSkeleton',
  inject: {
    components: {
      default: {
        CvSkeletonText,
        CvAccordionItemSkeleton,
      },
    },
  },
};
</script>
```

**Comment by lee-chase** [comment]
Could make a version soon
https://github.com/vuejs/vue/pull/8143

**Comment by sabov** [comment]
Hey @lee-chase, I'm not sure about the benefit as well. I would vote for using `functional` only in dead simple components without any dependencies.

**Comment by lee-chase** [comment]
OK @sabov we can return to functional if the above issue gets fixed.

Is this ready to merge, or do you need to undo any changes made for functional components?

**Comment by sabov** [comment]
It's good to go. I've used `functional` only in `_cv-accordion-item-skeleton.vue` and it works well.

**Comment by lee-chase** [comment]
> It's good to go. I've used `functional` only in `_cv-accordion-item-skeleton.vue` and it works well.

Revert functional for now in case of other issues.

**Pull request merged**
