### PR TITLE
feat: cv search

### PR DESCRIPTION
**Pull request by davidnixon**
Contributes to #1495

## What did you do?

Port cv-search to Vue3

## Were docs updated if needed?

- [x] Yes

### CODE REVIEW

**Comment by davidnixon** [comment]
@OlkaB could you review this one for me?

**Comment by OlkaB** [comment]
Will do today evening

**Comment by OlkaB** [comment]
@davidnixon adding CvSearch to main.js seems to be missing

**Review by OlkaB — COMMENTED** [review]
@davidnixon adding CvSearch to main.js seems to be missing

Other than that - all looks good to me 👍

(btw. how detailed reviews you're expecting? Should code work as expected or should I go into details like best code practices / patterns [which has potential to trigger discussions that will extend the time of a reviews] ?)

**Review by OlkaB — APPROVED** [review]

**Comment by davidnixon** [comment]
Thank. I really should get rid of main.js. I was using it for some local testing but the real entry point for the build is index.js which uses a regular expression to find all the components during the build.

And yes I'm open to all comments around best practices & patterns. 

FWIW, I do want to turn on more linting for the components. 
currently we use `plugin:vue/vue3-essential` but in other projects I use `plugin:vue/vue3-recommended` which enforces some more best practices. Currently turning that on shows 244 issues across 60 files :-(. I thought maybe best to finish the first full versions of the components before tackling a cleanup round.

**Comment by OlkaB** [comment]
I'm fully supporting the idea of improvements to be implemented after the components are fully ported to Vue3 and all potential issues are being fixed if ineeded. For me it will be a game changer when we will be upgrading large web apps we have in our Company to Vue3 without the need to move them at the same time to new UI lib.

**Pull request merged**
